[package]
name = "httpserver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
minijinja = "2.5.0"
tracing = "0.1.41"
tracing-subscriber = {version="0.3", features=["env-filter"]}

